project_id = "nqagezwcpdqkoalewnge"

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.cleanup-empty-conversations]
verify_jwt = false
